using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Configuration;

namespace DXApplication3
{
    public partial class Loaisanpham : Form
    {
        private DialogResult diaRe;
        public Loaisanpham()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // loaispTableAdapter1.Fill(aocuoiDataSet1.LOAISP);
        }
        private void LOaISPBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            this.Validate();
            this.lOAISPBindingSource.EndEdit();
            this.tableAdapterManager.UpdateAll(this.aocuoiDataSet);

        }


        private void Loaisanpham_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'aocuoiDataSet.LOAISP' table. You can move, or remove it, as needed.
            this.lOAISPTableAdapter.Fill(this.aocuoiDataSet.LOAISP);
            XuLyButton(true);
        }
        public void XuLyButton(bool b)
        {
            this.ma_textEdit1.Enabled = ten_textEdit2.Enabled = mota_textEdit3.Enabled = groupControl1.Enabled = b;

        }
        

        private void btn_them_CheckedChanged(object sender, EventArgs e)
        {
            XuLyButton(true);
            ma_textEdit1.Focus();
            this.lOAISPBindingSource.AddNew();
            this.tableAdapterManager.UpdateAll(this.aocuoiDataSet);

          
        }

        private void btn_xoá_CheckedChanged(object sender, EventArgs e)
        {
            //XuLyButton(true);
            //ma_textEdit1.Focus();
           /* if ( DialogResult.Yes == MessageBox.Show("Bạn có chắc muốn xoá hay không?", "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question))
            {
                this.lOAISPBindingSource.RemoveCurrent();
                this.tableAdapterManager.UpdateAll(this.aocuoiDataSet);
            }*/
            DataRow dr = gridView1.GetFocusedDataRow();
            DialogResult diaRe = MessageBox.Show("xác nhận xoá loại sản phẩm: " + dr[0].ToString(), "xác nhận xoá", MessageBoxButtons.YesNo, MessageBoxIcon.Warning, MessageBoxDefaultButton.Button2);
            //DialogResult diaRe = XtraMessageBox.Show("Xác nhận xóa thể loại: " + dr[1].ToString(), "Xác nhận xóa", MessageBoxButtons.YesNo, MessageBoxIcon.Warning, MessageBoxDefaultButton.Button2);
          
            if (diaRe == System.Windows.Forms.DialogResult.Yes)
            {
                try
                {
                    gridView1.DeleteSelectedRows();
                    btn_luu.Enabled = true;
                    //simpleButton_saveData.Enabled = true;
                }
                catch (Exception ex)
                {

                    MessageBox.Show(ex.Message);
                }
            }

        }

        private void btn_sua_CheckedChanged(object sender, EventArgs e)
        {
            /*if (DialogResult.Yes == MessageBox.Show("Bạn có chắc muốn xoá hay không?", "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question))
            {
                this.lOAISPBindingSource.RemoveCurrent();
                this.tableAdapterManager.UpdateAll(this.aocuoiDataSet);
            }*/
            //XuLyButton(true);
             //ma_textEdit1.Focus();
           // editDataRow();
            DataRow dr = gridView1.GetFocusedDataRow();
            DialogResult diaRe = MessageBox.Show("xác nhận sửa loại sản phẩm: " + dr[0].ToString(), "xác nhận sửa", MessageBoxButtons.YesNo, MessageBoxIcon.Warning, MessageBoxDefaultButton.Button2);
            //DialogResult diaRe = XtraMessageBox.Show("Xác nhận xóa thể loại: " + dr[1].ToString(), "Xác nhận xóa", MessageBoxButtons.YesNo, MessageBoxIcon.Warning, MessageBoxDefaultButton.Button2);

            if (diaRe == System.Windows.Forms.DialogResult.Yes)
            {
                try
                {
                    gridView1.UpdateColumnsCustomization();
                   // gridView1.DeleteSelectedRows();
                   // btn_sua.Enabled = true;
                    
                   btn_luu.Enabled = true;
                   

                    //simpleButton_saveData.Enabled = true;
                  
                }
                catch (Exception ex )
                {

                    MessageBox.Show(ex.Message);
                }
            }
        }

       
        private void btn_luu_CheckedChanged(object sender, EventArgs e)
        {
             if (ma_textEdit1.Text.Length ==0)
                 MessageBox.Show("Mã loại san pham không được bỏ trống!");
             else
                 if (ma_textEdit1.Text.Length>10)
                     MessageBox.Show("Mã loại sản phẩm không được lớn hơn 10!");
                 else
                     if (ten_textEdit2.Text.Length ==0)
                         MessageBox.Show("Tên sản phẩm không được bỏ trống");
                     else
                     {
                         try
                         {
                             this.Validate();
                             this.lOAISPBindingSource.EndEdit();
                             this.tableAdapterManager.UpdateAll(aocuoiDataSet);
                             XuLyButton(true);
                         }
                         catch (Exception ex)
                         {
                             MessageBox.Show("Mã loại sản phẩm" + ma_textEdit1.Text + "đã tồn tại", ex.Message);
                         }
                     }
        }

        private void btn_thoat_CheckedChanged(object sender, EventArgs e)
        {
            if (DialogResult.Yes == MessageBox.Show("Bạn có chắc muốn thoát hay không?", "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question))
            {
                this.lOAISPBindingSource.CancelEdit();
                this.Close();
                XuLyButton(true);
            }
        }

      

        
    }
}

